# Generated by Django 5.0.7 on 2025-03-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
    ]
