# Generated by Django 5.0.7 on 2025-03-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0002_delete_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'Manager chat',
                'verbose_name_plural': 'Manager chats',
            },
        ),
    ]
