# Generated by Django 5.0.7 on 2025-04-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Can be empty if mailing has attachment', max_length=4096, null=True, verbose_name='Text')),
                ('date_time', models.DateTimeField(blank=True, help_text='Date/time of mailing', null=True, verbose_name='Date/time')),
                ('is_sent', models.BooleanField(default=False, help_text='sending status', verbose_name='sending status')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], max_length=10, verbose_name='Type of attachment')),
                ('file', models.FileField(upload_to='', verbose_name='Attached file/video/photo')),
                ('file_id', models.CharField(blank=True, help_text='Leave empty. Delete to update media.', max_length=255, null=True, verbose_name='File ID')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='admin_panel.mailing', verbose_name='mailing')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
