# Generated by Django 5.0.7 on 2025-09-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_mailing_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
            ],
            options={
                'verbose_name': 'Daily Sales Report',
                'verbose_name_plural': 'Daily Sales Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_panel.managerchat',),
        ),
    ]
