# Generated by Django 5.0.7 on 2025-03-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Title')),
                ('category', models.CharField(choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('offers', 'Offers')], max_length=50, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('amount', models.IntegerField(blank=True, help_text='For codes and popularity', null=True, verbose_name='Amount')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active?')),
                ('is_automatic', models.BooleanField(blank=True, null=True, verbose_name='Automatic?')),
            ],
        ),
        migrations.CreateModel(
            name='OffersItem',
            fields=[
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='PopularityItem',
            fields=[
            ],
            options={
                'verbose_name': 'Popularity',
                'verbose_name_plural': 'Popularity Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='PUBGUCItem',
            fields=[
            ],
            options={
                'verbose_name': 'PUBG UC',
                'verbose_name_plural': 'PUBG UC Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='StockCodesItem',
            fields=[
            ],
            options={
                'verbose_name': 'GIFTCARD/CODE',
                'verbose_name_plural': 'GIFTCARDS & CODES',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
    ]
