# Generated by Django 5.0.7 on 2025-03-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftcardItem',
            fields=[
            ],
            options={
                'verbose_name': 'Giftcards item',
                'verbose_name_plural': 'Giftcards items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.AlterModelOptions(
            name='stockcodesitem',
            options={'verbose_name': 'STOCKBLE CODES', 'verbose_name_plural': 'STOCKBLE CODES'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('offers', 'Offers'), ('giftcard', 'Giftcard')], max_length=50, verbose_name='Category'),
        ),
    ]
