# Generated by Django 5.0.7 on 2025-03-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_initial'),
        ('items', '0003_giftcarditem_alter_stockcodesitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVoteItem',
            fields=[
            ],
            options={
                'verbose_name': 'HOME VOTE',
                'verbose_name_plural': 'HOME VOTE Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.managerchat', verbose_name='Chat for notifications'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard')], max_length=50, verbose_name='Category'),
        ),
    ]
