# Generated by Django 5.0.7 on 2025-03-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_initial'),
        ('items', '0004_homevoteitem_item_chat_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='admin_panel.managerchat', verbose_name='Chat for notifications'),
        ),
    ]
