# Generated by Django 5.0.7 on 2025-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(blank=True, choices=[(10, '10'), (60, '60'), (180, '180'), (325, '325'), (385, '385'), (660, '660'), (720, '720'), (985, '985'), (1320, '1320'), (1800, '1800'), (1920, '1920'), (3850, '3850'), (8100, '8100'), (16200, '16200'), (24300, '24300'), (32400, '32400')], help_text='For codes and popularity', null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_automatic',
            field=models.BooleanField(default=False, verbose_name='Automatic?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, help_text='Not obligatory. Has priority in the display in the menu', null=True, verbose_name='Title'),
        ),
    ]
