# Generated by Django 5.0.7 on 2025-04-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_amount_alter_item_is_automatic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_automatic',
        ),
        migrations.AddField(
            model_name='item',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS')], help_text='if not selected, then manual activation', null=True, verbose_name='Activator'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price'),
        ),
    ]
