# Generated by Django 5.0.7 on 2025-05-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_item_is_automatic_item_activator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiamondItem',
            fields=[
            ],
            options={
                'verbose_name': 'Mobilelegends diamond',
                'verbose_name_plural': 'Mobilelegends diamonds',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='StarItem',
            fields=[
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Star Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional data'),
        ),
        migrations.AlterField(
            model_name='item',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne')], help_text='if not selected, then manual activation', null=True, verbose_name='Activator'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(blank=True, choices=[(10, '10'), (60, '60'), (180, '180'), (325, '325'), (385, '385'), (660, '660'), (720, '720'), (985, '985'), (1320, '1320'), (1800, '1800'), (1920, '1920'), (3850, '3850'), (8100, '8100'), (11950, '11950'), (16200, '16200'), (24300, '24300'), (32400, '32400'), (40500, '40500')], help_text='For codes and popularity', null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond')], max_length=50, verbose_name='Category'),
        ),
    ]
