# Generated by Django 5.0.7 on 2025-07-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_diamonditem_staritem_item_data_alter_item_activator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond')], default='codes', max_length=50, verbose_name='Category')),
                ('title', models.CharField(max_length=35, verbose_name='Title')),
                ('ordering_id', models.SmallIntegerField(blank=True, null=True, verbose_name='Ordering num')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['ordering_id', 'category', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='diamonditem',
            options={'verbose_name': 'MLBB Russia', 'verbose_name_plural': 'MLBB Russia'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-price', 'title']},
        ),
        migrations.AddField(
            model_name='item',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.folder', verbose_name='Folder'),
        ),
    ]
