# Generated by Django 5.0.7 on 2025-09-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_folder_alter_diamonditem_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price', 'title']},
        ),
        migrations.AlterField(
            model_name='item',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne'), ('ucodeium', 'UCodeium')], help_text='if not selected, then manual activation', null=True, verbose_name='Activator'),
        ),
    ]
