# Generated by Django 5.0.7 on 2025-09-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_options_alter_item_activator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Button Name')),
                ('prompt_text', models.CharField(help_text='e.g., "Input your PUBG ID" or "Enter your Riot ID (Name#Tag)"', max_length=255, verbose_name='Player ID Prompt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('ordering', models.PositiveSmallIntegerField(default=100, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Manual Order Category',
                'verbose_name_plural': 'Manual Order Categories',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ManualItem',
            fields=[
            ],
            options={
                'verbose_name': 'Manual Order Item',
                'verbose_name_plural': 'Manual Order Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(blank=True, choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond'), ('more_pubg', 'More PUBG Services Folder')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond'), ('more_pubg', 'More PUBG Services Folder')], max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='manual_category',
            field=models.ForeignKey(blank=True, help_text='Select only for manual order items', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.manualcategory', verbose_name='Manual Category'),
        ),
    ]
