# Generated by Django 5.0.7 on 2025-09-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_manualcategory_manualitem_alter_folder_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorePubgItem',
            fields=[
            ],
            options={
                'verbose_name': 'More PUBG Service Item',
                'verbose_name_plural': 'More PUBG Service Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
    ]
