# Generated by Django 5.0.7 on 2025-09-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_folder_category_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond'), ('more_pubg', 'More PUBG Services')], max_length=50, unique=True, verbose_name='Category')),
                ('description', models.TextField(blank=True, help_text='This text will be shown at the top of the selected category menu.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category Description',
                'verbose_name_plural': 'Category Descriptions',
            },
        ),
        migrations.AddField(
            model_name='manualcategory',
            name='description',
            field=models.TextField(blank=True, help_text='This text will be shown at the top of this category menu.', verbose_name='Description'),
        ),
    ]
