# Generated by Django 5.0.7 on 2025-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0006_alter_item_amount_alter_item_is_automatic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockbleCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updation date')),
                ('amount', models.IntegerField(choices=[(10, '10'), (60, '60'), (325, '325'), (660, '660'), (1800, '1800'), (3850, '3850'), (8100, '8100'), (16200, '16200'), (32400, '32400'), (24300, '24300'), (40500, '40500')], verbose_name='Nominal')),
            ],
            options={
                'verbose_name': 'PUBG STOCKBLE CODE',
                'verbose_name_plural': 'PUBG STOCKBLE CODES',
            },
        ),
        migrations.CreateModel(
            name='UcCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updation date')),
                ('amount', models.PositiveIntegerField(choices=[(10, '10'), (60, '60'), (180, '180'), (325, '325'), (385, '385'), (660, '660'), (720, '720'), (985, '985'), (1320, '1320'), (1800, '1800'), (1920, '1920'), (3850, '3850'), (8100, '8100'), (16200, '16200'), (24300, '24300'), (32400, '32400')], verbose_name='Nominal')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='API status')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Is used')),
                ('is_success', models.BooleanField(blank=True, null=True, verbose_name='Is activated successfully')),
            ],
            options={
                'verbose_name': 'UC activating code',
                'verbose_name_plural': 'UC activating codes',
            },
        ),
        migrations.CreateModel(
            name='Giftcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updation date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giftcard_codes', to='items.giftcarditem', verbose_name='Item in menu')),
            ],
            options={
                'verbose_name': 'GIFTCARD',
                'verbose_name_plural': 'GIFTCARDS',
            },
        ),
    ]
