# Generated by Django 5.0.7 on 2025-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codes', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_codes', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='stockblecode',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockble_codes', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='uccode',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uc_codes', to='orders.order', verbose_name='Order'),
        ),
    ]
