# Generated by Django 5.0.7 on 2025-04-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uccode',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS')], help_text='if not selected, then any', null=True, verbose_name='Activator'),
        ),
    ]
