# Generated by Django 5.0.7 on 2025-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_uccode_activator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uccode',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne')], help_text='if not selected, then any', null=True, verbose_name='Activator'),
        ),
        migrations.AlterField(
            model_name='uccode',
            name='amount',
            field=models.PositiveIntegerField(choices=[(10, '10'), (60, '60'), (180, '180'), (325, '325'), (385, '385'), (660, '660'), (720, '720'), (985, '985'), (1320, '1320'), (1800, '1800'), (1920, '1920'), (3850, '3850'), (8100, '8100'), (11950, '11950'), (16200, '16200'), (24300, '24300'), (32400, '32400'), (40500, '40500')], verbose_name='Nominal'),
        ),
    ]
