# Generated by Django 5.0.7 on 2025-09-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_alter_uccode_activator_alter_uccode_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uccode',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne'), ('ucodeium', 'UCodeium')], help_text='if not selected, then any', null=True, verbose_name='Activator'),
        ),
    ]
