# Generated by Django 5.0.7 on 2025-09-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_alter_uccode_activator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatorPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne'), ('ucodeium', 'UCodeium')], max_length=20, unique=True, verbose_name='Activator Name')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number means higher priority (e.g., 0 is first, 1 is second).', verbose_name='Priority Order')),
            ],
            options={
                'verbose_name': 'Activator Priority',
                'verbose_name_plural': 'Activator Priorities',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='uccode',
            name='is_priority_use',
            field=models.BooleanField(db_index=True, default=False, help_text='These codes will be used before regular stock.', verbose_name='Priority Use'),
        ),
        migrations.AlterField(
            model_name='uccode',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne'), ('ucodeium', 'UCodeium')], help_text='Filled automatically after successful activation', null=True, verbose_name='Successful Activator'),
        ),
    ]
