# Generated by Django 5.0.7 on 2025-09-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_activatorpriority_uccode_is_priority_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatorpriority',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
