# Generated by Django 5.0.7 on 2025-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0006_alter_item_amount_alter_item_is_automatic_and_more'),
        ('users', '0003_alter_tguser_first_name_alter_tguser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updation date')),
                ('data', models.JSONField(verbose_name='Item data')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('category', models.CharField(choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard')], verbose_name='Category')),
                ('pubg_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='PUBG id')),
                ('is_completed', models.BooleanField(blank=True, null=True, verbose_name='Completed/Failed')),
                ('message_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Message id')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance before order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item', verbose_name='Item')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tguser', verbose_name='TG USER')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount to topup')),
                ('comission', models.DecimalField(blank=True, decimal_places=3, max_digits=4, verbose_name='Comission')),
                ('to_pay', models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Total to pay')),
                ('tx_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='txId')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('is_topped', models.BooleanField(default=False, verbose_name='Topped')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updation date')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tguser', verbose_name='TG USER')),
            ],
            options={
                'verbose_name': 'TopUp',
                'verbose_name_plural': 'TopUps',
                'ordering': ('-id',),
            },
        ),
    ]
