# Generated by Django 5.0.7 on 2025-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond')], verbose_name='Category'),
        ),
    ]
