# Generated by Django 5.0.7 on 2025-09-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond'), ('more_pubg', 'More PUBG Services')], verbose_name='Category'),
        ),
    ]
