# Generated by Django 5.0.7 on 2025-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('RUB', 'RUB')], default='USDT', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Payment URL'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='comission',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Comission'),
        ),
    ]
